version: '3.3'
services:
  github-scraper:
    build: ./target/docker/stage
    environment:
      GITHUB_SCRAPER_PORT: '8181'
      GITHUB_USERNAME: '${GITHUB_USERNAME}'
      GITHUB_TOKEN: '${GITHUB_TOKEN}'
      GITHUB_PASSWORD: '${GITHUB_PASSWORD}'
    ports:
      - '8181:8181'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'travis'
      MYSQL_PASSWORD: 'timetoscrape'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: